version: '3.7'

volumes:
  mongodata:

services:
     
  mongo:
    image: mongo:latest
    restart: always
   # build:
     # context: .
    volumes:
        - mongodata:/data/db
    container_name: mongo-express
    environment:
        #MONGO_DATA_DIR: /var/lib/mongo/data/mongodata
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
        MONGO_INITDB_DATABASE: express_db
    ports:
        - '27013:27013'
        
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #       - "8081:8081"
  #   environment:
  #       ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #       ME_CONFIG_MONGODB_ADMINPASSWORD: pass
